 /**
     * Extends the product class, adding a "healthRegen" field to represent the
     * health restored by the potion. Chains Product constructor to allow for
     * healthRegen field to be initialized from constructor.
     * 
     * @author Paul Bennett
     * @version 1.0
     * @since 11/19/21
     * 
     * @see Product
     */
    
public class Health extends Product{
   
    private int healthRegen;

    /**
     * Default constructor.
     */
    public Health() {

    }

    /**
     * Constructor with args to initialize instance variables on construction of the
     * Product.
     * 
     * @param name        The name of the product.
     * @param desc        A brief description of the product.
     * @param price       The current sell price of the product.
     * @param qty         The quantity of the item in stock at the storefront.
     * @param healthRegen The amount of health regenerated by the potion.
     */
    public Health(String name, String desc, double price, int qty, int healthRegen) {
        super(name, desc, price, qty);
        this.healthRegen = healthRegen;
    }

    /**
     * Sets the amount of health that the potion will regenerate.
     * 
     * @param healthRegen The amount of health to regenerate.
     */
    public void setHealthRegen(int healthRegen) {
        this.healthRegen = healthRegen;
    }

    /**
     * Returns the amount of health that the potion will regenerate.
     * 
     * @return The amount of health to regenerate.
     */
    public int getHealthRegen() {
        return healthRegen;
    }
}
